/* Generated by Cython 0.29.37 */

#ifndef __PYX_HAVE_API__pycylon__api__lib
#define __PYX_HAVE_API__pycylon__api__lib
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"

static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_context)(PyObject *) = 0;
#define pyclon_is_context __pyx_api_f_7pycylon_3api_3lib_pyclon_is_context
static std::shared_ptr<cylon::CylonContext>  (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_context)(PyObject *) = 0;
#define pycylon_unwrap_context __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_context
static std::shared_ptr<cylon::net::MPIConfig>  (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_mpi_config)(PyObject *) = 0;
#define pycylon_unwrap_mpi_config __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_mpi_config
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_mci_communicator)(std::shared_ptr<cylon::net::MPICommunicator>  const &) = 0;
#define pycylon_wrap_mci_communicator __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_mci_communicator
static std::shared_ptr<cylon::Table>  (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_table)(PyObject *) = 0;
#define pycylon_unwrap_table __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_table
static std::shared_ptr<cylon::DataType>  (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_data_type)(PyObject *) = 0;
#define pycylon_unwrap_data_type __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_data_type
static cylon::io::config::CSVReadOptions (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_csv_read_options)(PyObject *) = 0;
#define pycylon_unwrap_csv_read_options __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_csv_read_options
static cylon::io::config::CSVWriteOptions (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_csv_write_options)(PyObject *) = 0;
#define pycylon_unwrap_csv_write_options __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_csv_write_options
static std::shared_ptr<cylon::SortOptions>  (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_sort_options)(PyObject *) = 0;
#define pycylon_unwrap_sort_options __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_sort_options
static std::shared_ptr<cylon::BaseArrowIndex>  (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_base_arrow_index)(PyObject *) = 0;
#define pycylon_unwrap_base_arrow_index __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_base_arrow_index
static cylon::Type (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_type)(PyObject *) = 0;
#define pycylon_unwrap_type __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_type
static cylon::Layout (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_layout)(PyObject *) = 0;
#define pycylon_unwrap_layout __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_layout
static cylon::join::config::JoinConfig *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_join_config)(PyObject *) = 0;
#define pycylon_unwrap_join_config __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_join_config
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_table)(std::shared_ptr<cylon::Table>  const &) = 0;
#define pycylon_wrap_table __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_table
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_context)(std::shared_ptr<cylon::CylonContext>  const &) = 0;
#define pycylon_wrap_context __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_context
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_type)(cylon::Type const &) = 0;
#define pycylon_wrap_type __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_type
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_layout)(cylon::Layout const &) = 0;
#define pycylon_wrap_layout __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_layout
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_data_type)(std::shared_ptr<cylon::DataType>  const &) = 0;
#define pycylon_wrap_data_type __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_data_type
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_sort_options)(std::shared_ptr<cylon::SortOptions>  const &) = 0;
#define pycylon_wrap_sort_options __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_sort_options
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_base_arrow_index)(std::shared_ptr<cylon::BaseArrowIndex>  const &) = 0;
#define pycylon_wrap_base_arrow_index __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_base_arrow_index
static std::shared_ptr<cylon::Column>  (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_column)(PyObject *) = 0;
#define pycylon_unwrap_column __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_column
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_column)(std::shared_ptr<cylon::Column>  const &) = 0;
#define pycylon_wrap_column __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_column
static std::shared_ptr<cylon::Scalar>  (*__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_scalar)(PyObject *) = 0;
#define pycylon_unwrap_scalar __pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_scalar
static PyObject *(*__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_scalar)(std::shared_ptr<cylon::Scalar>  const &) = 0;
#define pycylon_wrap_scalar __pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_scalar
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_table)(PyObject *) = 0;
#define pyclon_is_table __pyx_api_f_7pycylon_3api_3lib_pyclon_is_table
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_mpi_config)(PyObject *) = 0;
#define pyclon_is_mpi_config __pyx_api_f_7pycylon_3api_3lib_pyclon_is_mpi_config
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_csv_read_options)(PyObject *) = 0;
#define pyclon_is_csv_read_options __pyx_api_f_7pycylon_3api_3lib_pyclon_is_csv_read_options
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_csv_write_options)(PyObject *) = 0;
#define pyclon_is_csv_write_options __pyx_api_f_7pycylon_3api_3lib_pyclon_is_csv_write_options
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_type)(PyObject *) = 0;
#define pyclon_is_type __pyx_api_f_7pycylon_3api_3lib_pyclon_is_type
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_layout)(PyObject *) = 0;
#define pyclon_is_layout __pyx_api_f_7pycylon_3api_3lib_pyclon_is_layout
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_data_type)(PyObject *) = 0;
#define pyclon_is_data_type __pyx_api_f_7pycylon_3api_3lib_pyclon_is_data_type
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_sort_options)(PyObject *) = 0;
#define pyclon_is_sort_options __pyx_api_f_7pycylon_3api_3lib_pyclon_is_sort_options
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_join_config)(PyObject *) = 0;
#define pyclon_is_join_config __pyx_api_f_7pycylon_3api_3lib_pyclon_is_join_config
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_base_arrow_index)(PyObject *) = 0;
#define pyclon_is_base_arrow_index __pyx_api_f_7pycylon_3api_3lib_pyclon_is_base_arrow_index
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_column)(PyObject *) = 0;
#define pyclon_is_column __pyx_api_f_7pycylon_3api_3lib_pyclon_is_column
static int (*__pyx_api_f_7pycylon_3api_3lib_pyclon_is_scalar)(PyObject *) = 0;
#define pyclon_is_scalar __pyx_api_f_7pycylon_3api_3lib_pyclon_is_scalar
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction_0_29_37
#define __PYX_HAVE_RT_ImportFunction_0_29_37
static int __Pyx_ImportFunction_0_29_37(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
#if PY_VERSION_HEX >= 0x02070000
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
#else
    {const char *desc, *s1, *s2;
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);}
#endif
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_pycylon__api__lib(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("pycylon.api.lib");
  if (!module) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_context", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_context, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_context", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_context, "std::shared_ptr<cylon::CylonContext>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_mpi_config", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_mpi_config, "std::shared_ptr<cylon::net::MPIConfig>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_mci_communicator", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_mci_communicator, "PyObject *(std::shared_ptr<cylon::net::MPICommunicator>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_table", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_table, "std::shared_ptr<cylon::Table>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_data_type", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_data_type, "std::shared_ptr<cylon::DataType>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_csv_read_options", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_csv_read_options, "cylon::io::config::CSVReadOptions (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_csv_write_options", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_csv_write_options, "cylon::io::config::CSVWriteOptions (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_sort_options", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_sort_options, "std::shared_ptr<cylon::SortOptions>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_base_arrow_index", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_base_arrow_index, "std::shared_ptr<cylon::BaseArrowIndex>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_type", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_type, "cylon::Type (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_layout", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_layout, "cylon::Layout (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_join_config", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_join_config, "cylon::join::config::JoinConfig *(PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_table", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_table, "PyObject *(std::shared_ptr<cylon::Table>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_context", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_context, "PyObject *(std::shared_ptr<cylon::CylonContext>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_type", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_type, "PyObject *(cylon::Type const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_layout", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_layout, "PyObject *(cylon::Layout const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_data_type", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_data_type, "PyObject *(std::shared_ptr<cylon::DataType>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_sort_options", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_sort_options, "PyObject *(std::shared_ptr<cylon::SortOptions>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_base_arrow_index", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_base_arrow_index, "PyObject *(std::shared_ptr<cylon::BaseArrowIndex>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_column", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_column, "std::shared_ptr<cylon::Column>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_column", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_column, "PyObject *(std::shared_ptr<cylon::Column>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_unwrap_scalar", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_unwrap_scalar, "std::shared_ptr<cylon::Scalar>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pycylon_wrap_scalar", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pycylon_wrap_scalar, "PyObject *(std::shared_ptr<cylon::Scalar>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_table", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_table, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_mpi_config", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_mpi_config, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_csv_read_options", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_csv_read_options, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_csv_write_options", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_csv_write_options, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_type", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_type, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_layout", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_layout, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_data_type", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_data_type, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_sort_options", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_sort_options, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_join_config", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_join_config, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_base_arrow_index", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_base_arrow_index, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_column", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_column, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_37(module, "pyclon_is_scalar", (void (**)(void))&__pyx_api_f_7pycylon_3api_3lib_pyclon_is_scalar, "int (PyObject *)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__pycylon__api__lib */
